services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - REACT_APP_SOCKET_URL=http://localhost:5001
    networks:
      - qr-restaurant-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - qr-restaurant-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - qr-restaurant-network

networks:
  qr-restaurant-network:
    driver: bridge

volumes:
  mongodb_data:
